server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbuser
    username: dbuser
    password: Admin123
    hikari:
      initialization-fail-timeout: -1

  liquibase:
    change-log: classpath:data/liquibase/dbchangelog.xml
    parameters:
      key: bigint
  data:
    mongodb:
      host: localhost
      database: videogames
      username: mongo
      password: Admin123
      authentication-database: admin
  rabbitmq:
    username: rabbit
    password: Admin123
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    org:
      hibernate:
        type: trace