server:
  port: 8081
spring:
  datasource:
    url: jdbc:h2:tcp://localhost:9090/mem:dev;MODE=LEGACY
    username: dbuser
    password: letmein
    driver-class-name: org.h2.Driver
  liquibase:
    change-log: classpath:data/liquibase/dbchangelog.xml
    parameters:
      key: bigint
  data:
    mongodb:
      host: localhost
      database: videogames
      username: mongo
      password: Admin123
      authentication-database: admin
  rabbitmq:
    username: rabbit
    password: Admin123
  jpa:
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  
